name: bmlp
channels:
  - nvidia 
  - conda-forge
  - rapidsai
  - defaults

dependencies:
  - python
  - numpy
  - cudf
  - cudatoolkit
  - python-graphblas
  - ipykernel
  - pip
  - tqdm
  - scikit-learn