name: bmlp
channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - ipykernel
  - tqdm
  ## GraphBLAS python wrapper 
  - python-graphblas
  ## For GPU support
  - cudatoolkit
  - pytorch=*=*cuda*
  ## for data analysis and visualisation
  - scikit-learn
  - matplotlib