name: bmlp
channels:
  - nvidia 
  - conda-forge
  # - pytorch

dependencies:
  - python
  - pip
  - numpy
  - pandas
  - python-graphblas
  - ipykernel
  - tqdm
  ## for data analysis and visualisation
  - scikit-learn
  - matplotlib
  ## Use conda install pytorch=*=*cuda* cudatoolkit -c pytorch 
  ## for faster conda solving time
  # - cudatoolkit
  # - pytorch=*=*cuda*
  ## Optional
  # - cudf