name: bmlp
channels:
  - nvidia 
  - conda-forge
  # - pytorch

dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - python-graphblas
  - ipykernel
  - tqdm
  ## for data analysis and visualisation
  - scikit-learn
  - matplotlib
  ## Use conda install pytorch=*=*cuda* cudatoolkit -c pytorch 
  ## for faster conda solving time
  # - cudatoolkit
  # - pytorch=*=*cuda*
  ## Use conda install rapids=25.02 -c rapidsai -c conda-forge -c nvidia 
  # - rapids=25.02