name: bmlp
channels:
  - nvidia 
  - conda-forge
  - rapidsai
  - defaults

dependencies:
  - python >= 3.9
  - cudf
  - cudatoolkit
  - pygraphblas  # PyGraphBLAS from conda-forge
  - ipykernel
  - pip
